### ISSUE TITLE
test asteroid client errors

### ISSUE THREAD

**Issue by WALL-E** [astroport-fi/asteroid-protocol#53]
## test client 

```
npx asteroid marketplace list cft20 --ticker ROIDS --amount 10 --price 0.1 -n mainnet
```

## asteroid.json

```
{
    "gasPrice": "0.005uatom",
    "networks": {
        "local": {
            "chainId": "gaialocal-1",
            "rpc": "http://localhost:16657",
            "explorer": "http://localhost:1316/cosmos/tx/v1beta1/txs/",
            "api": "http://localhost:8080/v1/graphql"
        },
        "testnet": {
            "chainId": "theta-testnet-001",
            "rpc": "https://rpc.sentry-01.theta-testnet.polypore.xyz",
            "explorer": "https://www.mintscan.io/cosmoshub-testnet/tx/",
            "api": "https://testnet-api.asteroidprotocol.io/v1/graphql"
        },
        "mainnet": {
            "chainId": "cosmoshub-4",
            "rpc": "https://rpc-nodes.asteroidprotocol.io",
            "explorer": "https://www.mintscan.io/cosmos/tx/",
            "api": "https://api.asteroidprotocol.io/v1/graphql"
        }
    },
    "accounts": {
        "test1": {
            "mnemonic": "banner spread envelope side kite person disagree path silver will brother under couch edit food venture squirrel civil budget number acquire point work mass"
        }
    }
}
```

## return error info

```
/home/ec2-user/asteroid-protocol/client/node_modules/@cosmjs/tendermint-rpc/build/rpcclients/http.js:10
        throw new Error(`Bad status on response: ${res.status}`);
              ^

Error: Bad status on response: 522
    at filterBadStatus (/home/ec2-user/asteroid-protocol/client/node_modules/@cosmjs/tendermint-rpc/build/rpcclients/http.js:10:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpClient.execute (/home/ec2-user/asteroid-protocol/client/node_modules/@cosmjs/tendermint-rpc/build/rpcclients/httpclient.js:24:63)
    at async Tendermint37Client.detectVersion (/home/ec2-user/asteroid-protocol/client/node_modules/@cosmjs/tendermint-rpc/build/tendermint37/tendermint37client.js:61:26)
    at async Tendermint37Client.connect (/home/ec2-user/asteroid-protocol/client/node_modules/@cosmjs/tendermint-rpc/build/tendermint37/tendermint37client.js:50:26)
    at async connectComet (/home/ec2-user/asteroid-protocol/client/node_modules/@cosmjs/tendermint-rpc/build/tendermintclient.js:26:24)
    at async SigningStargateClient.connectWithSigner (file:///home/ec2-user/asteroid-protocol/client/node_modules/@asteroid-protocol/sdk/esm/client.js:26:29)
    at async createContext (file:///home/ec2-user/asteroid-protocol/client/node_modules/@asteroid-protocol/sdk/esm/context.js:52:20)
    at async action (file:///home/ec2-user/asteroid-protocol/client/node_modules/@asteroid-protocol/sdk/esm/cli.js:24:21)

Node.js v20.11.1
```

**Comment by tomashanacek** [comment]
Could be an issue with the RPC, did you try other public Cosmos Hub RPCs? 
You'll also need to define your account in `accounts` section of the `asteroid.json` to get things working

**Comment by tomashanacek** [comment]
Closing the issue, please reopen if issue persists. 
Feel free to contant us in Asteroid Devs telegram group https://t.co/gzWybw79su
